version: '3'
services:
  milvus:
    image: milvusdb/milvus
    container_name: milvus-standalone
    ports:
      - "19530:19530"
      - "19121:19121"
    environment:
      - MILVUS_LOG_LEVEL=debug
