@@ -1,11 +0,0 @@
version: '3'
services:
  milvus:
    image: milvusdb/milvus:cpu-latest
    container_name: milvus_cpu
    ports:
      - "19530:19530"
      - "19121:19121"
    environment:
      - MILVUS_LOG_LEVEL=debug
